name: Manage Railway Server

on:
  schedule:
    - cron: "42 21 25 * *" 
    - cron: "50 21 25 * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  manage-server:
    runs-on: ubuntu-latest

    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Start Railway Service
        if: ${{ github.event.schedule == '42 21 25 * *' }}
        run: |
          railway up --project 309a53f5-f0c3-488d-a0e7-0dd93a687ee5
          yarn install
          yarn start

      - name: Stop Railway Service
        if: ${{ github.event.schedule == '50 21 25 * *' }}
        run: railway down --project 309a53f5-f0c3-488d-a0e7-0dd93a687ee5