name: Manage Railway Server

on:
  schedule:
    - cron: "25 21 25 * *" 
    - cron: "30 21 25 * *"
  workflow_dispatch:

jobs:
  manage-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Start Railway Service
        if: ${{ github.event.schedule == '25 21 25 * *' }}
        run: |
          railway up --project <your-project-id>  # Підняти сервер
          yarn install  # Встановити залежності
          yarn start    # Запустити сервер

      - name: Stop Railway Service
        if: ${{ github.event.schedule == '30 21 25 * *' }}
        run: railway down --project <your-project-id> 